repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --extra dev ruff check --fix
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: uv run --extra dev ruff format
        language: system
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: uv run --extra dev mypy src
        language: system
        pass_filenames: false
      - id: bandit
        name: bandit
        entry: uv run --extra dev bandit -q -r src
        language: system
        pass_filenames: false
      - id: detect-secrets
        name: detect secrets
        entry: uv run --extra dev detect-secrets-hook --baseline .secrets.baseline
        language: system
        types: [text]
